name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.11'
    
    - name: Install OpenSim
      run: |
        wget https://github.com/opensim-org/opensim-core/releases/download/v4.3/OpenSim-4.3-2022-10-14-ubuntu-20.04.zip
        unzip OpenSim-4.3-2022-10-14-ubuntu-20.04.zip
        export OPENSIM_HOME=$PWD/OpenSim-4.3-2022-10-14-ubuntu-20.04
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Run tests
      run: |
        python -m pytest tests/ 